site_name: Screwdriver Guide
repo_url: https://github.com/screwdriver-cd/guide
repo_name: GitHub
site_description: All you need to know about Screwdriver and more
# Due to bug in MKDocs: https://github.com/mkdocs/mkdocs/issues/974
# strict: true
theme: yeti
copyright: Yahoo Inc. BSD-3-Clause

pages:
    - Home: 'index.md'
    - Architecture:
        - Overall: 'architecture/overall.md'
        - API: 'architecture/api.md'
        - Engines: 'architecture/execution-engines.md'
